"""Typed adapter boundary for execution and caller effects."""

from __future__ import annotations

import asyncio
from typing import Any, Protocol

from .._records import ToolResolution, TurnInput, UsageEntry


class Observer(Protocol):
    @property
    def cancelled(self) -> bool: ...
    @property
    def pending(self) -> set[asyncio.Task[Any]]: ...
    @property
    def inspection_only(self) -> bool: ...
    model: str

    def output(self, text: str) -> None: ...
    def reasoning(self, text: str, *, final: bool = False) -> None: ...
    def usage(self, entry: UsageEntry) -> None: ...
    def work_started(self, provider: str | None = None, model: str | None = None) -> None: ...
    def work_resolved(self, provider: str, requested: str, actual: str) -> None: ...
    def extension(self, name: str, payload: Any, fields: dict[str, Any]) -> None: ...
    def progress(self, data: Any) -> None: ...
    def fail(self, error: Exception) -> None: ...
    async def call_tool(self, tool: Any, call_id: str, arguments: dict[str, Any]) -> ToolResolution: ...


class Runtime(Protocol):
    async def execute(self, input: TurnInput, observer: Observer) -> None: ...
    async def settle(self, resolutions: list[ToolResolution]) -> None: ...
    async def snapshot(self) -> dict[str, Any]: ...
    async def restore(self, snapshot: dict[str, Any]) -> None: ...
    def request_cancel(self) -> None: ...
    async def close(self) -> None: ...
