"""Typed adapter boundary for execution and caller effects."""

from __future__ import annotations

import asyncio
from typing import Any, Protocol

from .._records import Tool, ToolResolution, TurnInput, UsageEntry


class Observer(Protocol):
    cancelled: bool
    pending: set[asyncio.Task[Any]]
    model: str

    def output(self, text: str) -> None: ...
    def reasoning(self, text: str, *, final: bool = False) -> None: ...
    def usage(self, entry: UsageEntry) -> None: ...
    def work_started(self) -> None: ...
    def extension(self, name: str, payload: Any, fields: dict[str, Any]) -> None: ...
    def fail(self, error: Exception) -> None: ...
    async def call_tool(self, tool: Tool, call_id: str, arguments: dict[str, Any]) -> str: ...


class Runtime(Protocol):
    async def execute(self, input: TurnInput, observer: Observer) -> None: ...
    async def settle(self, resolutions: list[ToolResolution]) -> None: ...
    def request_cancel(self) -> None: ...
    async def close(self) -> None: ...
