"""Embed an agent with typed turns, caller tools, and live events."""

from ._binding import Agent, Session, Turn, create_agent
from ._records import (
    BUILTIN_TOOLS,
    AgentError,
    AgentOptions,
    ApprovalDecision,
    ApprovalHandler,
    ApprovalRequest,
    ApprovalRequestEvent,
    ApprovalResolution,
    ApprovalResponse,
    ContentPart,
    ConversationMessage,
    Event,
    McpServer,
    OutputDelta,
    Progress,
    ReasoningDelta,
    ReasoningFinal,
    Selection,
    SessionOptions,
    SessionRecord,
    TextPart,
    Tool,
    ToolCall,
    ToolCallEvent,
    ToolContext,
    ToolFailed,
    ToolHandler,
    ToolOutcomeUnknown,
    ToolResolution,
    ToolResultEvent,
    TurnInfo,
    TurnInput,
    TurnRecord,
    TurnResult,
    TurnStarted,
    Usage,
    UsageEntry,
    UsageEvent,
)

__version__ = "1.0.0a1"
contract_version = "agent-interface/1"
contract_versions = ("agent-interface/1", "turn-events/1", "language-binding/1", "host-config/1")

__all__ = [
    "BUILTIN_TOOLS",
    "Agent",
    "AgentError",
    "AgentOptions",
    "ApprovalDecision",
    "ApprovalHandler",
    "ApprovalRequest",
    "ApprovalRequestEvent",
    "ApprovalResolution",
    "ApprovalResponse",
    "ContentPart",
    "ConversationMessage",
    "Event",
    "McpServer",
    "OutputDelta",
    "Progress",
    "ReasoningDelta",
    "ReasoningFinal",
    "Selection",
    "Session",
    "SessionOptions",
    "SessionRecord",
    "TextPart",
    "Tool",
    "ToolCall",
    "ToolCallEvent",
    "ToolContext",
    "ToolFailed",
    "ToolHandler",
    "ToolOutcomeUnknown",
    "ToolResolution",
    "ToolResultEvent",
    "Turn",
    "TurnInfo",
    "TurnInput",
    "TurnRecord",
    "TurnResult",
    "TurnStarted",
    "Usage",
    "UsageEntry",
    "UsageEvent",
    "contract_version",
    "contract_versions",
    "create_agent",
]
