"""Private operations connecting owned bindings to agent behavior."""

from __future__ import annotations

from collections.abc import AsyncIterator
from typing import Protocol

from ._records import (
    Event,
    SessionOptions,
    SessionRecord,
    TurnInfo,
    TurnInput,
    TurnRecord,
    TurnResult,
)


class TurnPort(Protocol):
    @property
    def info(self) -> TurnInfo: ...
    @property
    def final_history(self) -> list[TurnRecord]: ...
    def events(self) -> AsyncIterator[Event]: ...
    async def cancel(self) -> None: ...


class SessionPort(Protocol):
    @property
    def info(self) -> SessionRecord: ...
    @property
    def history(self) -> list[TurnRecord]: ...
    async def run(self, input: TurnInput) -> TurnResult: ...
    async def run_with_history(self, input: TurnInput) -> tuple[TurnResult, list[TurnRecord]]: ...
    async def start_turn(self, input: TurnInput) -> TurnPort: ...
    async def fork(self) -> SessionPort: ...
    async def close(self) -> None: ...


class AgentPort(Protocol):
    @property
    def contract_versions(self) -> tuple[str, ...]: ...
    async def create_session(self, options: SessionOptions | None = None) -> SessionPort: ...
    async def resume_session(self, session_id: str) -> SessionPort: ...
    async def list_sessions(self) -> list[SessionRecord]: ...
    async def delete_session(self, session_id: str) -> None: ...
    async def close(self) -> None: ...
